polyflix/frontend

.github/release-drafter.yml
.github/workflows/ci.yml
.github/workflows/label-checker.yml
.github/workflows/pr-title-checker.yml

ci: validate release drafter requirements

---

.github/release-drafter.yml
.github/workflows/ci.yml

ci: add secret input for reusable workflow

---

.npmrc

Closes #15 
Update the npm packages registry URL in .npmrc file with the following :
@polyflix:registry=https://npm.pkg.github.com

chore(#15): migrate to github npm registry

---

.github/release-drafter.yml

fix: release-drafter semver version-resolver labels

---

.github/workflows/e2e.yml

Signed-off-by: LeoFVO <leofvo@proton.me>

style(e2e): reword workflow name

---

src/modules/collections/components/CollectionTimeline/CollectionTimeline.component.tsx
src/modules/collections/components/CollectionTimeline/ItemCollectionTimeline.component.tsx

fix(#13): private element of a collection can not be clicked

---

.npmrc
package-lock.json
package.json

fix: update polyflix npm package

---

apps/polyflix/package.json
pnpm-lock.yaml

chore: bump @polyflix packages

---

apps/polyflix/src/environments/environment.ts
apps/polyflix/src/main.tsx
apps/polyflix/src/modules/authentication/auth.router.tsx
apps/polyflix/src/modules/authentication/pages/Mock.page.tsx
apps/polyflix/src/modules/authentication/pages/Redirect.page.tsx

refactor: rework conditions for authentication / mock

---

apps/polyflix/public/locales/en/videos.json
apps/polyflix/public/locales/fr/videos.json

Signed-off-by: leofvo <leofvo@proton.me>
Closes #

fix: bad display of videos count

---

apps/polyflix/src/modules/search/services/search.service.ts

fix: remove empty search call on page load

---

apps/polyflix/src/environments/environment.ts

fix: change keycloak environment variable

---

.github/workflows/package.yml
.github/workflows/release.yml

fix: package app on release

---

apps/polyflix/src/modules/core/components/ElementSmallTag/element-small-tag.component.tsx
apps/polyflix/src/modules/core/components/Icon/Icon.component.tsx
apps/polyflix/src/modules/core/components/VideoCard/video-card.component.tsx

feat: add likes (#74)

---

apps/polyflix/src/modules/core/components/Jumbotron/jumbotron.component.tsx

feat: home page searchbar v1 (#73)

---

apps/polyflix/src/modules/core/components/CardMenu/CardMenu.component.tsx
apps/polyflix/src/modules/users/pages/ProfileVideos/ProfileVideos.page.tsx

fix: remve info button and padding on more-vert button (#76)

---

apps/polyflix/public/locales/en/home.json

fix: typo (#77)

---

apps/polyflix/src/modules/core/components/Dashboard/Navbar/Navbar.component.tsx

feat: burger menu (#78)

---

apps/polyflix/src/modules/core/components/Dashboard/Navbar/Navbar.component.tsx

fix: handle close on click menu (#80)

---

apps/polyflix/src/modules/core/components/VideoCard/video-card.component.tsx

feat: video views (#75)

---

apps/polyflix/src/modules/core/pages/Home.page.tsx

fix: home page courses query page need to be 1 or more

---

apps/polyflix/src/modules/core/components/Dashboard/Navbar/Navbar.component.tsx

feat: add logout button (#68)

---

apps/polyflix/src/modules/core/components/ListVideoCard/list-video-card.component.tsx

feat: remove view from video list card  (#75)

---

apps/polyflix/src/environments/environment.ts
apps/polyflix/src/modules/authentication/pages/Mock.page.tsx
packages/mock-server/index.ts

fix(#96): redirection on mock server after login

---

apps/polyflix/public/locales/en/common.json
apps/polyflix/public/locales/fr/common.json
apps/polyflix/src/modules/core/components/Footer/footer.component.tsx
apps/polyflix/src/modules/core/pages/Home.page.tsx

build: footer + fix jumbotron theme

---

apps/polyflix/src/modules/core/components/Header/Header.component.tsx
apps/polyflix/src/modules/users/pages/ProfileAttachments/ProfileAttachments.page.tsx
apps/polyflix/src/modules/users/pages/ProfileCertifications/ProfileCertifications.page.tsx
apps/polyflix/src/modules/users/pages/ProfileCollections/ProfileCollections.page.tsx
apps/polyflix/src/modules/users/pages/ProfileCourses/ProfileCourses.page.tsx
apps/polyflix/src/modules/users/pages/ProfileQuizzes/ProfileQuizzes.page.tsx
apps/polyflix/src/modules/users/pages/ProfileVideos/ProfileVideos.page.tsx

fix(#92): profile page UI padding too large

---

apps/polyflix/public/locales/en/users.json
apps/polyflix/public/locales/fr/users.json
apps/polyflix/src/modules/core/components/CardInformation/card-information.component.tsx

feat(video): view publisher profile

---

apps/polyflix/src/modules/videos/pages/[create-update].page.tsx

fix(#95): buttons style and padding improvements

---

apps/polyflix/src/modules/core/components/Dashboard/Navbar/Navbar.component.tsx
apps/polyflix/src/modules/core/components/Jumbotron/jumbotron.component.tsx

Signed-off-by: leofvo <leofvo@proton.me>
Closes #70 
Closes #71 
Closes #106

fix(homepage): title ellipsis + wrap title + fix darkmode

---

apps/polyflix/src/main.tsx
apps/polyflix/src/modules/collections/components/CollectionTimeline/ItemCollectionTimeline.component.tsx
apps/polyflix/src/modules/core/components/Dashboard/Navbar/Navbar.component.tsx
apps/polyflix/src/modules/core/components/HasRoles/HasRoles.component.tsx
apps/polyflix/src/modules/core/components/Jumbotron/jumbotron.component.tsx
apps/polyflix/src/modules/videos/components/VideoSliderCard/VideoSliderCard.component.tsx

feat(studio): add roles on links and guard on router

---

apps/polyflix/public/locales/en/videos.json
apps/polyflix/public/locales/fr/videos.json
apps/polyflix/src/modules/videos/components/PlayerSidebar/NotesPanel/NotesPanel.component.tsx

feat: ctrl + s cmd for saving notes

---

apps/polyflix/src/modules/core/components/Dashboard/Navbar/Navbar.component.tsx
apps/polyflix/src/modules/core/components/Jumbotron/jumbotron.component.tsx
apps/polyflix/src/modules/users/pages/Profile/Profile.page.tsx
apps/polyflix/src/modules/videos/components/PlayerSidebar/NotesPanel/NotesPanel.component.tsx
apps/polyflix/src/modules/videos/components/VideoDescription/VideoDescription.component.tsx
apps/polyflix/src/theme/palette.config.ts

feat: UI fix and improvements
